description: 'Creative Storytelling'
prompts: [prompt1.txt]
providers:
  - id: "mistral:mistral-medium"
    config:
      temperature: 0
      max_tokens: 1000
      safe_prompt: true
  - id: "openai:gpt-3.5-turbo-0613"
    config:
      temperature: 0
      max_tokens: 1000
  - id: "openai:gpt-4-0125-preview"
    config:
      temperature: 0
      max_tokens: 1000
tests:
  - vars:
      topic: "a mysterious island"
    assert:
      - type: cost
        threshold: 0.002
      - type: "contains-json"
        value:
          {
            'required': ['metadata', 'diary_entry'],
            'type': 'object',
            'properties': {
              'metadata': {
                'type': 'object',
                'required': ['name', 'location', 'date'],
                'properties': {
                  'name': { 'type': 'string' },
                  'location': { 'type': 'string' },
                  'date': { 'type': 'string', 'format': 'date' }
                }
              },
              'diary_entry': { 'type': 'string' }
            },
          }
  - vars:
      topic: "a futuristic city"
    assert:
      - type: answer-relevance
        value: "Ensure that the output contains content about a futuristic city"
      - type: "llm-rubric"
        value: "ensure that the output showcases innovation and detailed world-building"
  - vars:
      topic: "an ancient Egyptian civilization"
    assert:
      - type: "model-graded-closedqa"
        value: "References Egypt in some way"
